### ISSUE TITLE
Mouse coordinates broken without IMGUI_EXAMPLE_FORCE_DPI_FACTOR

### ISSUE THREAD

**Issue by Frenzie** [reduf/search#27]
That's on Kubuntu 23.04 with X11.

Also the UI remains too small regardless, but that's less bothersome. ;-)

**Comment by reduf** [comment]
I observe there is something really broken with hdpi, but have some difficulty debugging any of it without hardware to test it.

I know that I once disable hdpi for the app (possible on Mac and Windows, so presumably also on Kubuntu) which could be a workaround.

**Comment by Frenzie** [comment]
I might look into it a bit more in that case. Too bad the Rust compile times are quite off-putting. :-)

**Comment by reduf** [comment]
Yeah, I did some work to optimize it (replacing the image create by a c file), and trying to match the version of crates included in different branches of the dependency tree, but I agree that's not great overall.

I actually also did some work to use SDL instead of glium, but there is some drawbacks (e.g., size of the executable) and linking statically is also fairly slow.

In fact, I think the compile time is even worst on Linux than on Windows due to much more deps.

Anyway, if you find some fixes, I would really appreciate it and I will look into the other issue #28 you created.

**Comment by reduf** [comment]
Was fixed in https://github.com/reduf/search/tree/v0.8.0, will re-open if it wasn't correctly.

**Comment by Frenzie** [comment]
Something seems to have changed in the meantime. Now the mouse position's wrong unless I remove the division. 🤔  (Kubuntu 25.04 with both X11 and Wayland)
```diff
diff --git a/src/support.rs b/src/support.rs
index 6f1eca4..1ffed9d 100755
--- a/src/support.rs
+++ b/src/support.rs
@@ -267,7 +267,7 @@ impl System {
             Event::WindowEvent {
                 event: WindowEvent::CursorMoved { position, ..},
                 ..
-            } => imgui.io_mut().add_mouse_pos_event([(position.x as f32)/hidpi_factor, (position.y as f32)/hidpi_factor]),
+            } => imgui.io_mut().add_mouse_pos_event([(position.x as f32), (position.y as f32)]),
             event => {
                 if !app.handle_event(&window, &event) {
                     platform.handle_event(imgui.io_mut(), &window, &event);
```
